steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test','https://github.com/Chameleon-company/MOP-Acceptance-Tests/']
    # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test']
- name: 'gcr.io/google.com/docker'
  args: ['run']


# STEP 1 - CREATING STAGING ENVIRONMENT
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging','webapp/']
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging']
  # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'mop-code-webapp-staging'
   - '--image'
   - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging'
   - '--region'
   - 'australia-southeast1'
 

#  STEP 2 GOES HERE - ACCEPTANCE TESTING ON STAGING ENVIRONMENT




# STEP 3 - CREATING PRODUCTION ENVIRONMENT
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-testing','webapp/']
  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-testing']
  # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'mop-code-webapp-testing'
   - '--image'
   - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-testing'
   - '--region'
   - 'australia-southeast1'
images:
 - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-testing'
 - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-code-webapp-staging'
 - 'gcr.io/sit-22t1-city-of-melbo-d86dc19/mop-acceptance-test'