version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "melbourne-data-playground"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15sa8a759vnvg"
s3_prefix = "melbourne-data-playground"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["FlaskEntryPointFunction=119291007423.dkr.ecr.ap-southeast-2.amazonaws.com/melbournedataplaygroundfb654642/flaskentrypointfunctionc40eb309repo"]
